# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Adventures of kevans91
email: self@kyle-evans.net
description: > # this means to ignore newlines until "baseurl:"
  Documenting my various strictly programming adventures here, for the
  time being.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://kevans91.github.io" # the base hostname & protocol for your site
twitter_username: kaevans91
github_username:  kevans91

# Build settings
markdown: kramdown
